### ISSUE TITLE
BPM

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Pilot#1]
Starting to sketch out ideas. 

It would be good to pass the bpm to the underlying transport for note length, etc.

Maybe have a route /bpm that accepts the bpm and sets the tonejs bpm.

**Comment by neauoire** [comment]
I agree, remember tho, ORCA can only send OSC addresses of 1 in length(0-9a-z).

**Comment by cancel** [comment]
orca-c automatically sends `/orca/bpm 120` (or whatever) via OSC whenever the BPM is changed

**Comment by neauoire** [comment]
That's pretty clever. 
Will mirror.

**Comment by neauoire** [comment]
This will not be needed for Pilot after all.
