### ISSUE TITLE
No builds

### ISSUE THREAD

**Issue by aadilayub** [hundredrabbits/Pilot#10]
The documentation seems to indicate that there are builds available for Linux/OSX/Windows, but the link directs to the download page for Orca? Not sure if I'm missing something and there's a download link for Pilot somewhere on Orca's itch.io page.

**Comment by ryanramage** [comment]
Yes, at this point I have not released a build of Pilot yet. Its still in an early phase, but I will try and get some builds out soon. Unfortunately, the README was templated off of Orca and has some incorrect information. Sorry about that!

**Comment by neauoire** [comment]
Builds are up!
http://hundredrabbits.itch.io/Pilot
