### ISSUE TITLE
webaudio

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Pilot#2]
I just realized - tonejs is a webaudio dependent lib. I dont think there is a good node land webaudio impl yet.

So either

1. A electron instance is used. Maybe no window is launched? 
2. Some other headless chrome https://github.com/GoogleChrome/puppeteer

Just putting out ideas.

**Comment by ryanramage** [comment]
ugg, puppeteer is really big. ~170MB Mac, ~282MB Linux, ~280MB Win.

**Comment by neauoire** [comment]
I've set it up as an electron app, it'll display a UV visualizer  :)

**Comment by ryanramage** [comment]
ok great. Maybe waaaaay done the road it becomes the gateway of amazing visualizations :)

**Comment by neauoire** [comment]
I hope so :)
I was thinking maybe Marabu could be repurposed into a MIDI only tracker, and so Pilot could also be the companion synth to that project as well.
