### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Pilot#3]
I am eagerly following along... the commit about sounds I tried and I am not getting the any messages. I am using =A03C in orca, and I can see the following from the listener example:

```
 git:(master) ®[Orca]$ node listener.js
Started Listener

UDP:49160
OSC:49162

OSC server: A,0,4,12 from 127.0.0.1:52046 at /A
```

But I see no messages in pilot.

I dont  see this config section in Pilot,

```
const osc = require('./desktop/node_modules/node-osc')
const oscserver = new osc.Server(OSC_PORT, '127.0.0.1'
```

will that be needed?

**Comment by neauoire** [comment]
Use UDP `;` for now.

It should only play one note on bang so far.

Here's the roadmap:
https://github.com/hundredrabbits/Pilot#commands

**Comment by ryanramage** [comment]
ah ok. I see what you are doing. so the udp is just the raw buffer of the command. gotcha

**Comment by ryanramage** [comment]
Looks good. Roadmap helps me know what is still todo. I am going to come back to this and try and pick away at the todo things. Looking great!
