### ISSUE TITLE
Vertical Layout

### ISSUE THREAD

**Issue by dsiah** [hundredrabbits/Pilot#38]
I saw [a video](https://www.youtube.com/watch?v=OGdPkagBXks) where you (or rather Devine)  had Pilot in a different visual layout. 

I was wondering how to do this, and whether it may be a feature request for resizing the window in a longer vertical dimension or whether we could document the alt. layout on the README.

Thank you

**Comment by neauoire** [comment]
Ah yeah, I have to re-implement that one :) 
I will get right on it.
