### ISSUE TITLE
e and b notes not working

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Pilot#42]
Hi

Having fun with Orca and Pilot, it seems that e note and b note are out of order. Works when sending on midi from Orca to Helm.
```
aV2........Va........
.........1D2.........
.....................
.........1i8.........
..........7..........
.......Va.J..........
.......2..7..........
.......J..J..........
......D2..78TEeebebeb
.......Y.;22b3a......
..............I......
..............p......
.........Df...J......
..........;VIBp0.....
.....................
.........#.....#.....
.........;BIT1.......
.........;BIT0.......
```

**Comment by neauoire** [comment]
That should be fixed :) Could you update orca and try again?

**Comment by nlebellier** [comment]
Hi,

I pull Orca and Pilot and sadly same issue.

aV1........Va.........
.........1D1..........
..........*...........
.........1i8..........
..........5...........
.......Va.J...........
.......1..5...........
.......J..J...........
......D1..58TECeeABbb.
......*Y*;52B3a.......

Cheers

---
Nicolas








Le sam. 22 juin 2019 à 01:06, Лu Лinveгa <notifications@github.com> a
écrit :

**Comment by nlebellier** [comment]
Hi,

So i try with the latest version of both Orca and Pilot and get the same issue.
```
aV4........Va........
.........1D4.........
.....................
.........1i8.........
..........6..........
.......Va.J..........
.......4..6..........
.......J..J..........
......D4..68TECe.ebeb
.......Y.;22e3a......
```

**Comment by nlebellier** [comment]
Nickel !
Merci !
