### ISSUE TITLE
Trouble connecting Pilot to Orca via UDP

### ISSUE THREAD

**Issue by bobvanluijt** [hundredrabbits/Pilot#45]
I'm having some trouble connecting Pilot to Orca. Assuming from the documentation I need to send commands through [UDP port 49161](https://github.com/hundredrabbits/Pilot#commands). Any help would be appreciated because after some puzzling I seem unable to make some noise ;-)

I do this like this (note the UDP port I'm setting):

<img width="449" alt="Screenshot 2019-12-28 at 13 46 37" src="https://user-images.githubusercontent.com/5509162/71543869-89076900-2978-11ea-84a1-05ecbc83c487.png">

My OS = OSX Catalina

PS:
I did find [this](https://github.com/hundredrabbits/Pilot/issues/3) issue but I think it is outdated.

**Comment by neauoire** [comment]
To use Pilot, you must use the [UDP operator](https://github.com/hundredrabbits/Orca/blob/master/TUTORIAL.md#pilot), instead of the midi operator.

**Comment by bobvanluijt** [comment]
Thx
