### ISSUE TITLE
Change play route

### ISSUE THREAD

**Issue by ryanramage** [hundredrabbits/Pilot#8]
Its really handy when opening up orca files that are tied to midi to just change the `:` to `;` and have it play. I think I want to move the play command and drop the leading 'P' eg

Command | Channel | Octave | Note | Velocity | Length
-- | -- | -- | -- | -- | --
04C | 0 | 4 | C | 64 | 1/16
04Cf | 0 | 4 | C | 127 | 1/16
04Cff | 0 | 4 | C | 127 | 1bar

@neauoire thoughts?

**Comment by ryanramage** [comment]
Also in orca to match it would be handy either

 - a find and replace 
 - when you make a multi cursor (hold shift) if you type a char it fills in all grid positions with that char.

**Comment by neauoire** [comment]
yes, it's absolutely important that this transition works as is, since ultimately I'd like to package Pilot with Orca :) I like the multicursor fill idea. I'll try to implement that!

**Comment by neauoire** [comment]
The note length might change, I'm not sure if `0-f` is really the best thing right now.

**Comment by ryanramage** [comment]
Can you elaborate on the note length? I am not sure if I follow.

**Comment by ryanramage** [comment]
Made changes and now in master.
